import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * 1.测试String及编码	2.测试异常
 * @author pc
 *
 */
public class Test1 {
	public static void main(String[] args) throws UnsupportedEncodingException {
		String s1="`ID_`, `REF_ID_`, `PARENT_ID_`, `F_LOAN_BANK`, `F_LOAN_BANK_NAME`, `F_LOAN_SUB_BANK`, `F_LOAN_SUB_BANK_NAME`, `F_LOAN_AMOUNT`, `F_BUS_LOAN_AMOUNT`, `F_HFUND_LOAN_AMOUNT`, `F_LOAN_PERIOD`, `F_BUS_LOAN_PERIOD`, `F_HFUND_LOAN_PERIOD`, `F_BUS_LOAN_RATE`, `F_BUS_LOAN_RATE_NAME`, `F_BUS_LOAN_RATE_VALUE`, `F_HFUND_LOAN_RATE`, `F_HFUND_LOAN_RATE_NAME`, `F_HFUND_LOAN_RATE_VALUE`, `F_REFUND_METHOD`, `F_REFUND_METHOD_NAME`, `F_OLD_LOAN_BANK`, `F_OLD_LOAN_BANK_NAME`, `F_OLD_LOAN_AMOUNT`, `F_RECEIPT_BANK_ACCOUNT`, `F_RECEIPT_BANK`, `F_RECEIPT_BANK_NAME`, `F_REFUND_BANK_ACCOUNT`, `F_REFUND_BANK`, `F_REFUND_BANK_NAME`, `F_INSURANCE`, `F_INSURANCE_NAME`, `F_JF_ORDER_NUM`, `F_YCWQ_ORDER_NUM`, `F_REFUND_PERIOD`, `F_REFUND_PERIOD_NAME`, `F_PRODUCT_TYPE_ID`, `F_PRODUCT_TYPE_ID_NAME`, `F_PRODUCT_ID`, `F_PRODUCT_ID_NAME`, `F_LOAN_TYPE`, `F_LOAN_TYPE_NAME`, `F_B_LOAN_AMOUNT`, `F_B_BUS_LOAN_AMOUNT`, `F_B_HFUND_LOAN_AMOUNT`, `F_B_LOAN_PERIOD`, `F_B_BUS_LOAN_PERIOD`, `F_B_HFUND_LOAN_PERIOD`, `F_B_BUS_LOAN_RATE`, `F_B_BUS_LOAN_RATE_NAME`, `F_B_BUS_LOAN_RATE_VALUE`, `F_B_HFUND_LOAN_RATE`, `F_B_HFUND_LOAN_RATE_NAME`, `F_B_HFUND_LOAN_RATE_VALUE`, `F_B_REFUND_METHOD`, `F_B_REFUND_METHOD_NAME`, `F_B_REFUND_PERIOD`, `F_B_REFUND_PERIOD_NAME`, `F_BANK_AUDIT_RESULT`, `F_BANK_AUDIT_RESULT_NAME`, `F_CUSTOMER_ACCEPT`, `F_CUSTOMER_ACCEPT_NAME`, `F_FOLLOW_UP_PROCESS`, `F_FOLLOW_UP_PROCESS_NAME`, `F_OLD_LOAN_SUB_BANK`, `F_OLD_LOAN_SUB_BANK_NAME`, `F_RECEIPT_SUB_BANK`, `F_RECEIPT_SUB_BANK_NAME`, `F_REFUND_SUB_BANK`, `F_REFUND_SUB_BANK_NAME`, `F_BANK_SIGN_TYPE`, `F_BANK_SIGN_TYPE_NAME`, `F_ADVANCE_CONTRACT_DATE`, `F_HAS_NET_SIGN`, `F_HAS_NET_SIGN_NAME`, `F_HAS_EVALUATE`, `F_HAS_EVALUATE_NAME`, `F_HAS_NOTARY`, `F_HAS_NOTARY_NAME`, `F_SERVICE_DEPT`, `F_SERVICE_DEPT_NAME`, `F_SIGN_ADDRESS`, `F_SIGN_LOCATION`, `F_SIGN_LOCATION_NAME`, `F_MEDIATION_COMPANY`, `F_MEDIATION_COMPANY_NAME`, `F_MEDIATION_BOARD`, `F_MEDIATION_INFO`, `F_DESCP`, `F_MEDIATION_GROUP`, `F_MEDIATION_GROUP_NAME`, `F_BANK_HANDLER_INFO`, `F_INITIAL_EVAL_BOOK_DATE`, `F_INITIAL_EVAL_BOOK_DESCP`, `F_INITIAL_EVAL_OUT_DATE`, `F_INITIAL_EVAL_OUT_DESCP`, `F_RECEIVE_DATA_DATE`, `F_RECEIVE_DATA_DESCP`, `F_HAS_SENT_FOR_SCREENING`, `F_HAS_SENT_FOR_SCREENING_NAME`, `F_SENT_FOR_SCREENING_DATE`, `F_CHANGE_LOAN_TYPE`, `F_CHANGE_LOAN_TYPE_NAME`, `F_RELEVANT_INFORMATION`, `F_AGREE_LOAN_DATE`, `F_AGREE_LOAN_DESCP`, `F_FINAL_EVAL_BOOK_DATE`, `F_FINAL_EVAL_BOOK_DESCP`, `F_LENDING_PREMISE`, `F_HAS_LENDING_PREMISE`, `F_HAS_LENDING_PREMISE_NAME`, `F_HAS_BANK_SEE_SIGN`, `F_HAS_BANK_SEE_SIGN_NAME`, `F_BUYER_DATA`, `F_BUYER_DATA_NAME`, `F_SELLER_DATA`, `F_SELLER_DATA_NAME`, `F_SIGN_CONTRACT_DATE`, `F_SIGN_CONTRACT_DESCP`, `F_OUT_CONTRACT_DATE`, `F_OUT_CONTRACT_DESCP`, `F_RETURN_CONTRACT_DATE`, `F_RETURN_CONTRACT_DESCP`, `F_TAKE_CER_WAY`, `F_TAKE_CER_WAY_NAME`, `F_TAKE_CER_WAY_DESCP`, `F_HOUSING_HANDLER`, `F_CUSTOMER_REALNAME`, `F_GUARANTEE_COMPANY`, `F_GUARANTEE_COMPANY_NAME`, `F_EVALUATION_COMPANY`, `F_EVALUATION_COMPANY_NAME`, `F_RISK_POINT`, `F_RISK_POINT_NAME`, `F_GENJIAN`, `F_GENJIAN_NAME`, `F_GENJIAN_PHONE`, `F_QIANJIAN`, `F_QIANJIAN_NAME`, `F_QIANJIAN_PHONE`, `F_DELIVER_TYPE`, `F_DELIVER_TYPE_NAME`, `F_CANCELLATION_DATE`, `F_CANCELLATION_DESCP`, `F_PAY_TAXES_DATE`, `F_PAY_TAXES_DESCP`, `F_DELIVER_DATE`, `F_DELIVER_DESCP`, `F_EXPECTED_NEW_CERT_DATE`, `F_EXPECTED_NEW_CERT_DESCP`, `F_NEW_CERT_DATE`, `F_NEW_CERT_DESCP`, `F_ARCHIVE_DATE`, `F_ARCHIVE_DESCP`, `F_IMPAWN_DATE`, `F_IMPAWN_DESCP`, `F_EXPECTED_CTZ_DATE`, `F_EXPECTED_CTZ_DESCP`, `F_CTZ_DATE`, `F_CTZ_DESCP`, `F_SEND_MAKE_LOANS_DATE`, `F_SEND_MAKE_LOANS_DESCP`, `F_MAKE_LOANS_DATE`, `F_MAKE_LOANS_DESCP`, `F_REFUND_DATA_DATE`, `F_REFUND_DATA_DESCP`, `F_CLOSE_CASE_DATE`, `F_CLOSE_CASE_DESCP`, `F_FINAL_EVAL_OUT_DATE`, `F_FINAL_EVAL_OUT_DESCP`, `F_HOUSING_ASSIGN_DATE`, `F_STATUS`, `F_HAS_EVALUATION_FEE`, `F_HAS_EVALUATION_FEE_NAME`, `F_EVALUATION_FEE_DESCP`, `F_RECALL_DESCP`, `F_HAND_OVER_DESCP`, `F_HAS_EVALUATION_REPORT`, `F_HAS_EVALUATION_REPORT_NAME`, `F_REPORT_HANDLE_TYPE`, `F_REPORT_HANDLE_TYPE_NAME`, `F_EVALUATION_REPORT_NUM`, `F_HAVE_FEES`, `F_EXPENSE_FEES`, `F_NEED_PAY_FEES`, `F_REFUND_FEES`, `F_HAS_RESET_DELIVER`, `F_HAS_RESET_DELIVER_NAME`, `F_RESET_DELIVER_DESCP`, `F_CASE_NUMBER`, `F_NOTARY_OUT_DATE`, `F_NOTARY_OUT_DESCP`, `F_NOTARY_RECEIVE_DATE`, `F_NOTARY_RECEIVE_DESCP`, `F_NET_SIGN_DATE`, `F_NET_SIGN_DESCP`, `F_NET_SIGN_PIC`, `F_NET_SIGN_SEALED_DATE`, `F_NET_SIGN_SEALED_DESCP`, `F_NET_SIGN_RESCIND_DATE`, `F_NET_SIGN_RESCIND_PIC`, `F_NET_SIGN_RECEIVE_DATE`, `F_NET_SIGN_RECEIVE_DESCP`, `F_LOAN_USAGE`, `F_LOAN_USAGE_NAME`, `F_RECEIPT_BANK_ACCOUNT_USERNAME`, `F_REFUND_BANK_ACCOUNT_USERNAME`, `F_NETSIGN_CONTRACT_NUM`, `F_CUSTOMER_SELLER_REALNAME`, `F_LURU`, `F_LURU_NAME`, `F_MAIN_PRODUCT`, `F_MAIN_PRODUCT_NAME`, `F_HFUND_SPEED_UP`, `F_HFUND_SPEED_UP_NAME`, `F_HAS_SENT_FOR_SCREENING_HFUND`, `F_HAS_SENT_FOR_SCREENING_HFUND_NAME`, `F_SENT_FOR_SCREENING_BUS_DATE`, `F_SENT_FOR_SCREENING_HFUND_DATE`, `F_HFUND_REFUND_METHOD`, `F_HFUND_REFUND_METHOD_NAME`, `F_HFUND_REFUND_PERIOD`, `F_HFUND_REFUND_PERIOD_NAME`, `F_HFUND_AUDIT_RESULT`, `F_HFUND_AUDIT_RESULT_NAME`, `F_BUS_MAKE_LOANS_DATE`, `F_BUS_MAKE_LOANS_DESCP`, `F_HFUND_MAKE_LOANS_DATE`, `F_HFUND_MAKE_LOANS_DESCP`, `F_BUS_SEND_MAKE_LOANS_DATE`, `F_BUS_SEND_MAKE_LOANS_DESCP`, `F_HFUND_SEND_MAKE_LOANS_DATE`, `F_HFUND_SEND_MAKE_LOANS_DESCP`, `F_B_HFUND_REFUND_METHOD`, `F_B_HFUND_REFUND_METHOD_NAME`, `F_B_HFUND_REFUND_PERIOD`, `F_B_HFUND_REFUND_PERIOD_NAME`, `F_BUS_AGREE_LOAN_DATE`, `F_BUS_AGREE_LOAN_DESCP`, `F_HFUND_AGREE_LOAN_DATE`, `F_HFUND_AGREE_LOAN_DESCP`, `F_BUS_SIGN_CONTRACT_DATE`, `F_BUS_SIGN_CONTRACT_DESCP`, `F_HFUND_SIGN_CONTRACT_DATE`, `F_HFUND_SIGN_CONTRACT_DESCP`, `F_BUS_OUT_CONTRACT_DATE`, `F_BUS_OUT_CONTRACT_DESCP`, `F_HFUND_OUT_CONTRACT_DATE`, `F_HFUND_OUT_CONTRACT_DESCP`, `F_BUS_RETURN_CONTRACT_DATE`, `F_BUS_RETURN_CONTRACT_DESCP`, `F_HFUND_RETURN_CONTRACT_DATE`, `F_HFUND_RETURN_CONTRACT_DESCP`, `INST_ID_`, `INST_STATUS_`, `CREATE_USER_ID_`, `CREATE_GROUP_ID_`, `TENANT_ID_`, `CREATE_TIME_`, `UPDATE_TIME_`, `F_PROGRAMME_ID`, `F_PROGRAMME_ID_NAME`, `F_OPT_MGR_AUDIT_RESULT`, `F_HOUSING_HANDLER_NAME`, `F_BUS_REVIEW_DESCP`, `F_HFUND_REVIEW_DESCP`, `F_BUS_AGREE_LOAN_PART_DESCP`, `F_HFUND_AGREE_LOAN_PART_DESCP`, `F_SHANGSHU_DATE`, `F_SHANGSHU_ENTRUST_NUM`, `F_SHANGSHU_ENTRUST_PIC`, `F_SHANGSHU_DESCP`, `F_MEDIATION_INST_TYPE`, `F_YUYUE_DELIVER_DATE`, `F_QIANJIAN_DATE`, `F_OPT_MGR_AUDIT_DESCP`, `F_RETURN_CASE_DATE`, `F_RETURN_CASE_DESCP`, `F_CHANGBANKNEEDFLOW`, `F_ZUOJIAN`, `F_ZUOJIAN_NAME`, `F_CUSTOMER_ASSISTANT`, `F_CUSTOMER_ASSISTANT_NAME`, `F_PARTNER_GROUP_LEADER`, `F_PARTNER_GROUP_LEADER_NAME`, `F_SY_ORDER_NUM`, `F_CHANGE_MAIN_PRODUCT`, `F_CHANGE_MAIN_PRODUCT_NAME`";
		String s2="'2520000017251029', '0', NULL, '2510000002120003', '中国银行', '2510000009745528', '番禺支行', '600000', '', '600000', NULL, '', '240', '', NULL, '', '1', '按基准', '', '', '', '', '', NULL, '暂无', '', '', '暂无', '', '', '', '', '1911161100087636', '', '', '', '', '', '', '', '2', '公积金贷款', '600000', NULL, '600000', NULL, NULL, '240', NULL, NULL, '', '1', '按基准', '', NULL, NULL, NULL, NULL, '0', '', '0', NULL, '', '', '', '', '', '', '', '', '', '', NULL, '2', '否', '1', '是', '2', '否', '2520000010334286', '广州按揭-营销中心-外区业务区域-大番禺-市桥', '广州市番禺区亚运大道655号新安居建材中心七座202铺', '7', '市桥分部', '', '', '', '', '', '', '', '[{}]', '2019-12-06 00:00:00', '', '2019-11-19 00:00:00', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '2019-11-29 00:00:00', '', '', '2', '不需要', NULL, NULL, '', NULL, '', NULL, '2019-12-03 00:00:00', NULL, '2019-12-03 00:00:00', NULL, '2019-12-03 00:00:00', NULL, '1', '银行自取', '', '2510000009906784', '张韫竹', '', NULL, '2520000010314095', NULL, '', '', '2520000011220573', '何辉辉', '15914337121 ', '2510000009906656', '张洁', '18148787871', '4', '交易+抵押', NULL, '', '2020-03-13 00:00:00', '', '2020-03-13 00:00:00', '', '2020-03-19 00:00:00', '', '2020-03-19 00:00:00', '', '2020-03-19 00:00:00', '', '2020-03-13 00:00:00', '', '2020-03-19 00:00:00', '', '2020-03-19 00:00:00', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-12-02 00:00:00', '', NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', '否', '', '2019111600004', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', '购买二手住宅', '李蓉  ', '张韫竹 ', '19110041710', '李蓉', '2510000009906656', '张洁', '', '公积金入押放', NULL, NULL, '1', '资料已送公积金中心审核', NULL, '2019-11-20 00:00:00', '2', '等额本息', '1', '每月', '1', '完全同意', NULL, '', '2020-03-20 00:00:00', NULL, NULL, NULL, '2020-03-17 00:00:00', NULL, '2', '', '1', '每月', NULL, NULL, '2019-11-27 00:00:00', '', NULL, NULL, '2019-12-03 00:00:00', '', NULL, NULL, '2019-12-03 00:00:00', '', NULL, NULL, '2019-12-03 00:00:00', '', '2520000017251028', 'RUNNING', '2510000009906656', '2520000010334280', '2510000009694995', '2019-11-16 15:32:37', '2020-03-20 11:59:54', '2520000011770810', '默认方案', NULL, '王淑柳', NULL, '', NULL, '', '2019-11-22 00:00:00', 'LCPY0003429', '2520000017363157', '', '', NULL, '2019-11-16 00:00:00', NULL, NULL, NULL, NULL, '2510000009906656', '张洁', '2510000009906677', '蔡其燕', '2520000016866773', '无', '20190020874 ', NULL, NULL";
		String ss1[]=s1.split(",");
		String ss2[]=s2.split(",");
		System.out.println(ss1.length);
		System.out.println(ss2.length);
		for(int i=0;i<ss1.length;i++){
			System.out.println(ss1[i]+"--------"+ss2[i]);
		}
//		for(int i=1;i<34;i++){
//			System.out.print("@a"+i+",");
//		}
//		DecimalFormat ndf = new DecimalFormat("#,##0.00");
//		DecimalFormat ndf1 = new DecimalFormat("#,###");
//		System.out.println(ndf1.format(Double.parseDouble("12798998")));;
		
//		String y_m="2020-04";
//		int mon=Integer.parseInt(y_m.substring(5, 7));
//		int year=Integer.parseInt(y_m.substring(0, 4));
		
//		System.out.println(2680+2800+2600+3800+14400-320+1350+1700+5000+3000+3000+14400+800+8800+2000+850+0+11900+8800+3200+12800+4500+900+3100+2100);
//		test1();
//
//		System.out.println(new String("天河区".getBytes(),"UTF-8"));
//		test();
//		String s=URLDecoder.decode("%E7%AE%A1%E7%90%86%E5%91%98");
//		System.out.println(s);
	}
	/**
	 * 测试string的split、list的remove
	 * @author LongBro
	 * 2019年12月4日
	 * 下午3:40:12
	 */
	private static void test1() {
		List<HashMap<String, String>> list=new ArrayList();
		HashMap<String, String> map=new HashMap<String, String>();
		HashMap<String, String> map1=new HashMap<String, String>();
		map.put("name", 0+"");
		map1.put("name", "12");
		list.add(map1);
		list.add(map);
		System.out.println("List的长度为"+list.size());
		String ess[]="0,1,2".split(",");
		System.out.println(">>>>>>>>>>>"+ess.length);
		String css[]="3,4".split(",");
		for(int j=0;j<10;j++){
			System.out.println("j="+j);
			for(int i=0;i<ess.length;i++){
				System.out.println("i="+i);
				if(map.get("name").equals(ess[i])){
					list.remove(map);
					break;
				}
			}
		}
		
		for(int i=0;i<css.length;i++){
			System.out.println(i);
			if(map.get("name").equals(css[i])){
				list.remove(map);
				break;
			}
		}
		System.out.println("List的长度为"+list.size());
	}
	
	public static void test(){
		try{
			int i=0/0;
		}catch(Exception e){
			System.out.println(e.toString());
		}
	}
}
